

<MenuWidget>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, .8
        Rectangle:
            size: self.size
    Label:
        text: "Test"
        pos_hint: { "center_x": .5, "center_y": .6}
    Button:
        text: "OK"
        pos_hint: { "center_x": .5, "center_y": .3}
        # horizontal in percent, vertical
        size_hint: .2, .15
        on_press: root.parent.on_menu_button_pressed()
